### ISSUE TITLE
Error between HybridSessions and Blog

### ISSUE THREAD

**Issue by CptPillow** [silverstripe/silverstripe-hybridsessions#57]
Once activating Hybridsessions via adding the following lines:
$SS_SESSION_KEY = '*******';
HybridSession::init($SS_SESSION_KEY);

I receive an error when creating a new Blog Post.
The error I get is " There seems to have been a technical problem. Please click the back button, refresh your browser, and try again. "
That is with the environment set to dev and php_flag on.

as well as a bad request calling the following file: resources/silverstripe/admin/client/dist/js/bundle.js?m=1571310006:1

**Comment by robbieaverill** [comment]
Hi, thanks for taking the time to post to our issue tracker.

The issue tracker is reserved for reporting bugs and we don't provide support via the issue tracker. There are great [community support options](http://www.silverstripe.org/community/#introduction) where you can get help including [our forum](https://forum.silverstripe.org), [Stack Overflow (remember to tag as silverstripe)](http://stackoverflow.com/questions/tagged/silverstripe) and even [Slack](http://silverstripe.org/slack).

Sorry we can't be of more help and good luck resolving your problem!

**Comment by NightJar** [comment]
Hi @CptPillow - if you are reporting a bug, can you please provide information on what version of the module you're using, what version of the CMS you are using it with, and a step by step recount of how to reproduce the issue?

This module is in use with the blog module on a reasonably large number of sites that I'm aware of, and with the lack of the above listed details in your issue statement, I'm afraid this does seem project related (i.e. an integration/configuration issue) - a support request rather than a bug report.
